services:
  api:
    image: orgmembershipservice.api
    build:
      context: .
      dockerfile: src/OrgMembershipService.Api/Dockerfile
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      - ConnectionStrings__DefaultConnection=Host=users-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - Authentication__TokenValidationParameters__ValidIssuers__2=${KEYCLOAK_ISSUER}
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - booking-network
        
  users-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - booking-network
    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    ports:
      - "8082:8080"
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - keycloak-data:/opt/keycloak/data
    networks:
      - booking-network

volumes:
  pg-data:
  keycloak-data:

networks:
  booking-network:
    external: true
